In [7]:
import pandas as pd 
data1 = pd.read_feather("/home/user96/score_file/barra.fea")
data2 = pd.read_feather("/home/user96/score_file/hist_time_holiday.fea")

In [ ]:
data1

In [8]:
data2

,date,Code,day_T+1_amt,day_T+2_amt,day_T+3_amt,day_T+4_amt,day_T+5_amt,day_T+6_amt,day_T+7_amt,day_T+8_amt,...,quarter_cos,week_sin,week_cos,holiday_dragon_boat,holiday_labor_day,holiday_mid_autumn,holiday_national_day,holiday_new_year,holiday_qingming,holiday_spring_festival
0,20170103,000001,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,6.123234e-17,0.120537,0.992709,0,0,0,0,1,0,0
1,20170103,000002,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,6.123234e-17,0.120537,0.992709,0,0,0,0,1,0,0
2,20170103,000004,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,6.123234e-17,0.120537,0.992709,0,0,0,0,1,0,0
3,20170103,000005,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,6.123234e-17,0.120537,0.992709,0,0,0,0,1,0,0
4,20170103,000006,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,6.123234e-17,0.120537,0.992709,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10431962,20241231,688799,-0.345952,-0.345880,-0.261339,-0.350076,-0.340292,-0.339892,-0.349970,-0.317267,...,1.000000e+00,0.120537,0.992709,0,0,0,0,-1,0,0
10431963,20241231,688800,0.792668,0.734292,0.385844,0.695896,5.309447,6.753030,0.692366,0.542525,...,1.000000e+00,0.120537,0.992709,0,0,0,0,-1,0,0
10431964,20241231,688819,-0.336280,-0.346301,-0.307260,-0.313302,-0.344577,-0.317348,-0.199674,-0.306635,...,1.000000e+00,0.120537,0.992709,0,0,0,0,-1,0,0
10431965,20241231,688981,8.311086,6.452509,8.080392,4.295832,2.729125,5.615363,3.411596,1.434700,...,1.000000e+00,0.120537,0.992709,0,0,0,0,-1,0,0
10431966,20241231,689009,-0.287683,-0.203748,0.521727,-0.168933,-0.038230,-0.112791,-0.087211,0.417635,...,1.000000e+00,0.120537,0.992709,0,0,0,0,-1,0,0

In [9]:
# 只保留列名字带有holiday的列
data2 = data2[[col for col in data2.columns if 'holiday' in col or col in ['Code', 'date']]]
data2

,date,Code,holiday_dragon_boat,holiday_labor_day,holiday_mid_autumn,holiday_national_day,holiday_new_year,holiday_qingming,holiday_spring_festival
0,20170103,000001,0,0,0,0,1,0,0
1,20170103,000002,0,0,0,0,1,0,0
2,20170103,000004,0,0,0,0,1,0,0
3,20170103,000005,0,0,0,0,1,0,0
4,20170103,000006,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...
10431962,20241231,688799,0,0,0,0,-1,0,0
10431963,20241231,688800,0,0,0,0,-1,0,0
10431964,20241231,688819,0,0,0,0,-1,0,0
10431965,20241231,688981,0,0,0,0,-1,0,0
10431966,20241231,689009,0,0,0,0,-1,0,0

In [10]:
data2.to_feather("/home/user96/score_file/holiday.fea")

In [ ]:
# 然后用 merge 按照 date 和 Code 进行内连接（inner join，取交集）
df_merged = pd.merge(data2, data1, on=["date", "Code"], how="inner")
df_merged.to_feather("/home/user96/score_file/hist_time_barra.fea")
df_merged